name: b1simpflemobilewarehousing
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/nemethmik/b1simpflemobilewarehousing
author: Miklos Nemeth (Tiva11) <nemethmiklos1960@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  b1serviceflayer: ^1.0.2
  meta: ^1.1.7
  
dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
